V0 edits
pyronear/pyro-platform pull request #64
Opened 2021-07-11 19:58 UTC by pechouc

Hello!

This PR aims at introducing the following features / edits:

- Simplified alert screen without any frame being displayed;
- Simplified alert acknowledgement workflow with an intermediary confirmation modal;
- A limit to the number of frames being displayed in alert modals;
- The replacement, by the red alert marker, of the blue site marker. 

A few other small edits have been made:

- The number of devices displayed in the popup of each site marker is now variabilized (set to 4 initially);
- Some bugs that remained in relation with the alert workflow have been fixed. 

Many thanks in advance for the review!

2021-07-21 14:13 UTC, Akilditu requested changes
After re-testing there is no issue related to alert disappearance once acknowledged

2021-07-22 07:45 UTC, Akilditu approved these changes
Everything looks super fine to me !

2021-07-22 07:45 UTC, Akilditu commented on app/alerts.py
> +        if row['name'].replace('_', ' ').title() in sites_with_live_alerts:
nice 👍

2021-07-22 07:46 UTC, merged

2021-07-22 12:38 UTC, frgfm commented
@Akilditu don't forget to delete the branch once a PR is merged ;)